### PR TITLE
 Yohannes Deboch ( Tidy Verse Part 1)

### PR DESCRIPTION
**Pull request by jonygeta**

### CODE REVIEW

**Comment by javernw** [comment]
Hi Yohannes,
I extended your example of Tidyverse dplyr
[You can find it here](https://github.com/javernw/JWCUNYAssignments/blob/master/DATA607%20Tidyverse%20dplyr.Rmd)

**Comment by rg563** [comment]
Hi Yohannes and Javern,

I also added a bit to this:
Github: https://github.com/rg563/SPRING2019TIDYVERSE-1/blob/master/Ryan_Gordon_dplyr_edits.Rmd
RPubs: http://rpubs.com/rg563/491963

**Comment by jonygeta** [comment]
Hi Ryan 

Thank you adding value to the code .

**Comment by acatlin** [comment]
Thank you, Yohannes!

**Pull request merged**
